[package]
name = "way-two-fa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.5.0"
hmac = "0.12.1"
rand = "0.8.5"
sha1 = "0.10.6"
